# Generated by Django 3.2.9 on 2021-12-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harta', '0002_auto_20211204_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviz',
            old_name='valabailitate',
            new_name='data_finalizarii',
        ),
    ]
