# Generated by Django 3.2.6 on 2021-12-04 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camioane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_matriculare', models.CharField(max_length=7)),
                ('location', models.IntegerField()),
                ('masa_masurata', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lemne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipul_lemnului', models.TextField()),
                ('densitate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Aviz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emiterii', models.DateField()),
                ('valabailitate', models.DateTimeField()),
                ('volum', models.FloatField()),
                ('masa_calculata', models.FloatField()),
                ('id_camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harta.camioane')),
                ('id_lemne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harta.lemne')),
            ],
        ),
    ]
