# Generated by Django 3.2.6 on 2021-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camioane',
            name='location',
        ),
        migrations.AddField(
            model_name='camioane',
            name='latitudine',
            field=models.FloatField(default=45),
        ),
        migrations.AddField(
            model_name='camioane',
            name='longitudine',
            field=models.FloatField(default=25),
        ),
    ]
